cmake_minimum_required(VERSION 3.8)
project(car_planning)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(car_control_msgs REQUIRED)

add_executable(trapezoid_velocity_profile src/trapezoid_velocity_profile.cpp)
ament_target_dependencies(trapezoid_velocity_profile
  rclcpp
  std_msgs
  car_control_msgs
)
target_compile_features(trapezoid_velocity_profile PUBLIC cxx_std_17)
target_include_directories(trapezoid_velocity_profile PRIVATE include)

install(TARGETS
  trapezoid_velocity_profile
  DESTINATION lib/${PROJECT_NAME}
)

install(
  DIRECTORY config launch
  DESTINATION share/${PROJECT_NAME}
)

if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  ament_add_gtest(test_longitudinal_profile test/test_longitudinal_profile.cpp)
  target_include_directories(test_longitudinal_profile PRIVATE include)

  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
